language: node_js

node_js:
- node
- 'lts/*'

cache: npm

os:
  - linux
dist: xenial

sudo: true
services:
  - docker

before_install:
  - docker build -t andreic/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andreic/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "beanstalk-react"
  env: "BeanstalkReact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-248319281910"
  bucket_path: "beanstalk-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
